import { useState } from 'react';
import './App.css';

const projects = [
  { name:'Alpha Commerce', type:'FULL-STACK PLATFORM', image:'/user_dashboard.png', description:'A production-minded shopping experience with separate customer and admin workflows.', details:['Role-based JWT authentication','Razorpay payments + order tracking','S3-powered product image storage'], stack:['Spring Boot','React','PostgreSQL','AWS S3'], url:'https://github.com/ShreyaaPawar/alpha-ecommerce-website', accent:'coral' },
  { name:'DTO Generator', type:'DEVELOPER TOOL', image:'/main-ui.png', description:'A Java utility that turns JSON schemas into clean DTOs and mapping logic—without the repetitive manual work.', details:['Config-driven code generation','Handles nested objects and arrays','One-click dark-mode Swing UI'], stack:['Java','Jackson','Swing','JSON'], url:'https://github.com/ShreyaaPawar/APIAutomationTool', accent:'blue' },
  { name:'NewsMonkey', type:'API EXPERIENCE', image:null, description:'A responsive news reader that makes a continuously-updating API feel fast, focused, and easy to browse.', details:['Category-based news discovery','Infinite scrolling','Responsive React interface'], stack:['React','NewsAPI','Bootstrap'], url:'https://github.com/ShreyaaPawar/NewsMonkeyApp', accent:'lime' },
];

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <div className="site-shell">
    <header className="site-header"><a className="wordmark" href="#top"><span>SP</span> shreya pawar</a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? '×' : 'Menu'}</button><nav className={menuOpen ? 'nav nav--open' : 'nav'}><a href="#about">About</a><a href="#experience">Experience</a><a href="#work">Work</a><a href="#contact" className="nav-contact">Let’s talk <span>↗</span></a></nav></header>
    <main id="top">
      <section className="hero"><div className="hero-copy"><p className="eyebrow"><i /> JAVA BACKEND DEVELOPER · MUMBAI, INDIA</p><h1>Building the<br />systems that make<br /><em>things work.</em></h1><p className="hero-intro">I’m <strong>Shreya Pawar</strong>, a backend-focused engineer building reliable, secure software—from everyday product flows to high-volume financial systems.</p><div className="hero-actions"><a href="#work" className="button button--ink">See selected work <span>↓</span></a><a href="https://linkedin.com/in/shreya-pawar12" target="_blank" rel="noreferrer" className="button button--paper">LinkedIn <span>↗</span></a></div><div className="hero-meta"><a href="https://github.com/ShreyaaPawar" target="_blank" rel="noreferrer">GitHub ↗</a><span>Open to SDE opportunities</span></div></div><div className="hero-art"><span className="shape shape--coral" /><span className="shape shape--blue" /><span className="shape shape--lime" /><div className="portrait"><img src="/profile.jpg" alt="Shreya Pawar" /><div className="portrait-note"><span>Currently</span><strong>Staff Consultant<br />@ Oracle</strong></div></div><div className="float-card float-card--transactions"><b>150K+</b><span>daily transactions</span></div><div className="float-card float-card--uptime"><i /> <b>High-stakes<br />systems</b></div></div></section>
      <div className="ticker"><div>JAVA + SPRING BOOT <i>✦</i> API DESIGN <i>✦</i> DISTRIBUTED SYSTEMS <i>✦</i> PRODUCT THINKING <i>✦</i> JAVA + SPRING BOOT <i>✦</i> API DESIGN <i>✦</i></div></div>
      <section className="section about" id="about"><div className="section-heading"><p>01 · ABOUT</p><h2>Reliable by default.<br /><em>Curious by nature.</em></h2></div><div className="about-copy"><p>I care about the invisible part of a great product: the services, data flows, and thoughtful decisions that make it feel effortless.</p><p>Over 4+ years at Oracle Financial Services, I’ve helped build secure transaction flows used at scale—while always making time to explore the tools and patterns that can make an engineer’s work better.</p><a href="#experience">My experience <span>↓</span></a></div></section>
      <section className="section experience" id="experience"><div className="section-heading"><p>02 · EXPERIENCE</p><h2>Engineering for<br /><em>the real world.</em></h2></div><div className="experience-list"><article className="role role--featured"><div className="role-top"><p>2024 — NOW</p><span>Oracle Financial Services</span></div><h3>Staff Consultant<br /><em>Java Backend Developer</em></h3><div className="impact-grid"><p><b>150K+</b><span>daily netbanking transactions supported</span></p><p><b>10+</b><span>REST APIs designed for onboarding & transactions</span></p><p><b>2M+</b><span>fraudulent attempts prevented annually</span></p></div><ul><li>Built secure HDFC Netbanking flows and fraud-detection integrations across high-volume financial journeys.</li><li>Improved system resilience with rate limiting, request validation, session management, and production troubleshooting.</li><li>Mentored engineers, reviewed deployments, and helped keep releases dependable.</li></ul></article><article className="role"><div className="role-top"><p>2022 — 2024</p><span>Oracle Financial Services</span></div><h3>Associate Consultant</h3><p className="role-summary">Optimised UI and backend flows for EPI transactions, resolved production issues, improved application stability, and implemented RBI-mandated compliance changes.</p></article></div></section>
      <section className="section work" id="work"><div className="section-heading"><p>03 · SELECTED WORK</p><h2>Side projects with<br /><em>serious intent.</em></h2></div><div className="project-grid">{projects.map((project,index) => <article className={`project project--${project.accent}`} key={project.name}><div className="project-visual">{project.image ? <img src={project.image} alt={`${project.name} interface`} /> : <div className="news-visual"><span>THE<br />DAILY<br />BRIEF.</span><i>LIVE</i><p>Business · Tech · Culture</p></div>}</div><div className="project-body"><p className="project-type">0{index+1} · {project.type}</p><h3>{project.name}</h3><p className="project-description">{project.description}</p><ul>{project.details.map(detail => <li key={detail}>{detail}</li>)}</ul><div className="project-bottom"><div className="tag-list">{project.stack.map(item => <span key={item}>{item}</span>)}</div><a href={project.url} target="_blank" rel="noreferrer">Explore code ↗</a></div></div></article>)}</div></section>
      <section className="section proof"><div className="proof-intro"><p>04 · TOOLKIT</p><h2>Built with the<br /><em>right tools.</em></h2></div><div className="skill-grid"><div><b>Backend</b><p>Java, Spring Boot, Spring Security, Hibernate, JPA, REST APIs</p></div><div><b>Data</b><p>Oracle DB, PostgreSQL, MySQL, SQL</p></div><div><b>Cloud & delivery</b><p>AWS, Docker, Kubernetes, Maven, Git, CI/CD</p></div><div><b>Frontend</b><p>React, JavaScript, HTML, CSS</p></div></div></section>
      <section className="contact" id="contact"><p>LET’S BUILD SOMETHING THAT <em>MATTERS.</em></p><h2>Have a problem<br />worth solving?</h2><a href="mailto:shreyapawar451@gmail.com">Say hello <span>↗</span></a><div><span>shreyapawar451@gmail.com</span><a href="https://linkedin.com/in/shreya-pawar12" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://github.com/ShreyaaPawar" target="_blank" rel="noreferrer">GitHub ↗</a></div></section>
    </main><footer>© {new Date().getFullYear()} Shreya Pawar · Built with care in Mumbai.</footer>
  </div>;
}
export default App;
